site_name: pdnsAdmin Docs
site_url: http://pdnsadmin.com
repo_url: https://github.com/pdnsadmin/pdnsadmin-docs
theme: readthedocs
pages:
    - Home: index.md
    - Download: download.md
    - Setup: setup.md
    - Install from source: user-guide/installation.md
    - Contrubutions: contributions.md
    - Installation: user-guide/installation.md
