site_name: pdnsAdmin Docs
site_url: http://pdnsadmin.com
repo_url: https://github.com/pkchuyen/pdnsadmin-docs
theme: readthedocs
pages:
    - Home: index.md
    - Download: download.md
    - About: about.md
